version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-php
    volumes:
      - ./app:/var/www/html
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=docker"